
package vista;

/**
 *
 * @author SITARE
 */
public class AtenderCitaDoctor extends javax.swing.JInternalFrame {

    /**
     * Creates new form CrearCita
     */
    public AtenderCitaDoctor() {
        initComponents();
        jPanel2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdCita = new javax.swing.JTextField();
        btnBuscarPaciente = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIdentificacion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCodigoDoctor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNombrePaciente1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtObservacion = new javax.swing.JTextField();
        btnAtender = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cbNiveles = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        txtObservacionDiagnostico = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cbDiagnostico = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cbTratamientos = new javax.swing.JComboBox<>();
        txtDosis = new javax.swing.JTextField();
        btnTerminarCita = new javax.swing.JButton();
        btnAgregarDiagnostico = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setClosable(true);
        setTitle("ATENDER CITA");
        setMaximumSize(new java.awt.Dimension(32767, 32767));
        setPreferredSize(new java.awt.Dimension(828, 557));
        setVisible(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setForeground(new java.awt.Color(204, 255, 255));
        jPanel1.setDoubleBuffered(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, -1, -1));

        jLabel2.setText("Identificación");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));
        jPanel1.add(txtIdCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, 170, 30));

        btnBuscarPaciente.setText("Buscar");
        jPanel1.add(btnBuscarPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, -1, -1));

        jLabel3.setText("Id Cita");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, -1, -1));

        jLabel5.setText("Observaciones");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));
        jPanel1.add(txtIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 170, 30));

        jLabel6.setText("Código Doctor");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, -1, -1));
        jPanel1.add(txtCodigoDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, 170, 30));

        jLabel7.setText("Paciente");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
        jPanel1.add(txtNombrePaciente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 340, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("PACIENTE");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 190, 40));
        jPanel1.add(txtObservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 340, 80));

        btnAtender.setBackground(new java.awt.Color(0, 204, 0));
        btnAtender.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAtender.setText("Atender");
        btnAtender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtenderMouseClicked(evt);
            }
        });
        jPanel1.add(btnAtender, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 150, 40));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbNiveles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cbNiveles, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 180, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("ATENCIÓN ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 190, 40));

        jLabel9.setText("Observacioens");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel10.setText("Dosis");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, -1, -1));

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 180, 30));

        jLabel12.setText("Nivel");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));
        jPanel2.add(txtObservacionDiagnostico, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 210, 130));

        jLabel13.setText("Diagnóstico");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        cbDiagnostico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cbDiagnostico, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 180, 30));

        jLabel14.setText("Tratamiento");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, -1));

        jLabel15.setText("Tipo");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, -1, -1));

        cbTratamientos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cbTratamientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 180, 30));
        jPanel2.add(txtDosis, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 180, 40));

        btnTerminarCita.setBackground(new java.awt.Color(204, 102, 0));
        btnTerminarCita.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnTerminarCita.setText("Términar Cita");
        btnTerminarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarCitaActionPerformed(evt);
            }
        });
        jPanel2.add(btnTerminarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, 150, 40));

        btnAgregarDiagnostico.setBackground(new java.awt.Color(0, 204, 0));
        btnAgregarDiagnostico.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAgregarDiagnostico.setText("Agregar Diagnóstico");
        btnAgregarDiagnostico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarDiagnosticoActionPerformed(evt);
            }
        });
        jPanel2.add(btnAgregarDiagnostico, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 150, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 824, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("CancelarCitaDoctor");

        getAccessibleContext().setAccessibleName("CancelarCitaDoctor");
        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTerminarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarCitaActionPerformed
       
    }//GEN-LAST:event_btnTerminarCitaActionPerformed

    private void btnAgregarDiagnosticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarDiagnosticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarDiagnosticoActionPerformed

    private void btnAtenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtenderMouseClicked
        // TODO add your handling code here:
        jPanel2.setVisible(true);
    }//GEN-LAST:event_btnAtenderMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregarDiagnostico;
    public javax.swing.JButton btnAtender;
    public javax.swing.JButton btnBuscarPaciente;
    public javax.swing.JButton btnTerminarCita;
    public javax.swing.JComboBox<String> cbDiagnostico;
    public javax.swing.JComboBox<String> cbNiveles;
    public javax.swing.JComboBox<String> cbTipo;
    public javax.swing.JComboBox<String> cbTratamientos;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JTextField txtCodigoDoctor;
    public javax.swing.JTextField txtDosis;
    public javax.swing.JTextField txtIdCita;
    public javax.swing.JTextField txtIdentificacion;
    public javax.swing.JTextField txtNombrePaciente1;
    public javax.swing.JTextField txtObservacion;
    public javax.swing.JTextField txtObservacionDiagnostico;
    // End of variables declaration//GEN-END:variables
}
