CREATE DATABASE dbHospitalTec
USE dbHospitalTec

CREATE TABLE [CENTRO_ATENCION](
codigo INT IDENTITY(1,1) NOT NULL,
nombre VARCHAR(50)NOT NULL,
lugar VARCHAR(50) NOT NULL,
capacidad INT NOT NULL,
tipo VARCHAR(25) NOT NULL
);
